FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel

RUN  apt-get update && apt-get install git -y && apt-get clean

RUN cd /home/ \
    && export CUDA_HOME=/usr/local/cuda/ \
    && git clone https://github.com/ggerganov/llama.cpp && cd llama.cpp \
    && export LLAMA_CUBLAS=on

ADD libllama.so /home/llama.cpp/libllama.so

RUN export LLAMA_CPP_LIB="/home/llama.cpp/libllama.so" \
    &&  ls -lah $LLAMA_CPP_LIB \
    && pip uninstall llama-cpp-python \
    && CMAKE_ARGS="-DLLAMA_CLBLAST=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir

RUN cd /home/ \
    && git clone https://github.com/markus-seidl/novel-ai.git \
    && cd /home/novel-ai/dataset \
    && pip install -r requirements.txt \
    && python -m nltk.downloader punkt

RUN cd /home/novel-ai/dataset/sumi \
    && python llama_summarizer_v2.py
