base_model: google/gemma-7b-it
model_type: GemmaForCausalLM
tokenizer_type: GemmaTokenizer
trust_remote_code: true
load_in_8bit: false
load_in_4bit: false
strict: false
rl: dpo
chat_template: inst
datasets:
  - path: ./dataset
    split: train
    type: alpaca
test_datasets:
  - path: ./dataset
    split: test
    type: alpaca
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./model
adapter: qlora
lora_model_dir:
sequence_len: 1800
sample_packing: false
pad_to_sequence_len: false
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
#wandb_project: gemma
#wandb_entity:
#wandb_watch:
#wandb_name:
#wandb_log_model:
gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 5e-7
train_on_inputs: false
group_by_length: false
#bf16: true
#fp16: false
#tf32: true
gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false
warmup_steps: 100
evals_per_epoch: 1
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 10
max_steps: 10
debug:
deepspeed: deepspeed_configs/zero1.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
