#base_model: google/gemma-7b-it
#base_model: unsloth/gemma-7b-it
base_model: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true
load_in_8bit: true
# load_in_4bit: false
strict: false
# rl: dpo

dataset_processes: 8

chat_template: inst
datasets:
  - path: ./dataset
    type: alpaca
    split: train
    data_files:
      - data.jsonl

val_set_size: 0.01
dataset_prepared_path: ./prepared_dataset
output_dir: ./model

adapter: lora
lora_model_dir:
sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
#lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

wandb_project: novel-ai-01
wandb_entity:
wandb_watch:
wandb_name: tinyllama
wandb_log_model: checkpoint

gradient_accumulation_steps: 1

optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 5e-7
train_on_inputs: false
group_by_length: false

#bf16: true
#fp16: false
#tf32: true

gradient_checkpointing: true

early_stopping_patience:
resume_from_checkpoint:

logging_steps: 1
xformers_attention:
flash_attention: false

warmup_ratio: 0.5

micro_batch_size: 10

eval_steps: 100
num_epochs: 1
save_steps: 100
# max_steps: 1

debug:
# do use --use_deepspeed
deepspeed: deepspeed_configs/zero1.json

weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:


